version: '3.8'

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: gymshark
      MONGODB_ADVERTISED_HOSTNAME: mongo-host
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  consumer:
    build:
      context: .
      dockerfile: Dockerfile
      target: consumer
    environment:
      - DATABASE_USERNAME=admin
      - DATABASE_PASSWORD=admin
      - DATABASE_HOST=mongo
      - DATABASE_PORT=27017
      - DATABASE_NAME=hackernews
      - BASE_URL=https://hacker-news.firebaseio.com/v0
    depends_on:
      - mongo
  grpc:
    build:
      context: .
      dockerfile: Dockerfile
      target: grpc
    ports:
      - "9000:9000"
    environment:
      - GRPC_PORT=9000
      - DATABASE_USERNAME=admin
      - DATABASE_PASSWORD=admin
      - DATABASE_HOST=mongo
      - DATABASE_PORT=27017
      - DATABASE_NAME=hackernews
      - CACHE_ADDRESS=redis:6379
    depends_on:
      - mongo
      - redis
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: api
    ports:
      - "8080:8080"
    environment:
      - API_ADDRESS=:8080
      - GRPC_ADDRESS=grpc:9000
    depends_on:
      - grpc
