version: '3.8'

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: gymshark
      MONGODB_ADVERTISED_HOSTNAME: mongo-host
  consumer:
    build:
      context: .
      dockerfile: Dockerfile
      target: consumer
    environment:
      - DATABASE_USERNAME=admin
      - DATABASE_PASSWORD=admin
      - DATABASE_HOST=mongo
      - DATABASE_PORT=27017
      - DATABASE_NAME=hackernews
      - BASE_URL=https://hacker-news.firebaseio.com/v0
    depends_on:
      - mongo
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: api
    ports:
      - "8081:8080"
    environment:
      API_ADDRESS: ":8080"
    depends_on:
      - mongo