version: '3.7'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: gymshark
  consumer:
    build:
      context: .
      dockerfile: Dockerfile
      target: consumer
    environment:
      - DATABASE_USERNAME=admin
      - DATABASE_PASSWORD=admin
      - DATABASE_HOST=mongo
      - DATABASE_PORT=27017
      - DATABASE_NAME=hackernews
    depends_on:
      - mongo