version: '3.8'

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: gymshark
      MONGODB_ADVERTISED_HOSTNAME: mongo-host
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: test
      RABBITMQ_DEFAULT_PASS: test1234!
  publisher:
    build:
      context: .
      dockerfile: Dockerfile
      target: publisher
    environment:
      - CRON=*/10 * * * *
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=test
      - RABBITMQ_PASSWORD=test1234!
      - RABBITMQ_QUEUE_NAME=items
      - BASE_URL=https://hacker-news.firebaseio.com/v0
    depends_on:
      - rabbitmq
  consumer:
    build:
      context: .
      dockerfile: Dockerfile
      target: consumer
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=test
      - RABBITMQ_PASSWORD=test1234!
      - RABBITMQ_QUEUE_NAME=items
      - DATABASE_USERNAME=admin
      - DATABASE_PASSWORD=admin
      - DATABASE_HOST=mongo
      - DATABASE_PORT=27017
      - DATABASE_NAME=hackernews
    depends_on:
      - rabbitmq
      - mongo
  grpc:
    build:
      context: .
      dockerfile: Dockerfile
      target: grpc
    ports:
      - "9000:9000"
    environment:
      - GRPC_PORT=9000
      - DATABASE_USERNAME=admin
      - DATABASE_PASSWORD=admin
      - DATABASE_HOST=mongo
      - DATABASE_PORT=27017
      - DATABASE_NAME=hackernews
      - CACHE_ADDRESS=redis:6379
    depends_on:
      - mongo
      - redis
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: api
    ports:
      - "8080:8080"
    environment:
      - API_ADDRESS=:8080
      - GRPC_ADDRESS=grpc:9000
    depends_on:
      - grpc
