name: Test
on: [ pull_request ]
jobs:
  test:
    strategy:
      matrix:
        go-version: [ 1.17.x ]
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Test
        run: go test ./... -cover
      - name: Vet
        run: go vet ./...